version: '3.8'
services:
  backend:
    container_name: backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: ./backend
      dockerfile: dockerfile
      target: dev
    volumes:
      - ./backend/:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    expose:
      - 5000
    ports:
      - 5000:5000
    # command: npm run dev

  frontend:
    container_name: frontend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: ./frontend
      dockerfile: dockerfile
      target: dev
    environment:
      # This env var is need for hot reload https://github.com/facebook/create-react-app/issues/1049
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: 'development'
    volumes:
      - ./frontend/:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    # command: npm run start
