FROM node:14.17.6-alpine3.14 as dev

WORKDIR /usr/src/app/backend

COPY package.json ./

RUN npm install

CMD ["npm","run","dev"]
# ENTRYPOINT ["tail"]
# CMD ["-f","/dev/null"]


# FROM dev as prod

# WORKDIR /usr/src/app/frontend

# COPY ../frontend/package.json ./

# RUN npm install

# RUN npm run build

